## This playbook:
## Updates the APT package cache to ensure it has the latest package information.
## Adds a PPA repository for additional packages.
## Imports a GPG key needed for package verification (although this might not be necessary for Ubuntu and is included here for illustrative purposes).
## Installs Node.js and npm from the default repositories.
## Ensures the ufw firewall service is stopped (useful in testing environments).
## Installs the forever package globally to ensure a Node.js application runs continuously.
## By running this playbook, you can set up a Ubuntu system with the necessary tools and configurations to develop and run a Node.js application.


- name: Install and configure repositories and packages on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install EPEL equivalent on Ubuntu (universe repository)
      apt_repository:
        repo: "ppa:deadsnakes/ppa"
        state: present

    - name: Import Remi GPG key (if needed)
      apt_key:
        url: "https://rpms.remirepo.net/RPM-GPG-KEY-remi2018"
        state: present

    - name: Install Node.js and npm
      apt:
        name: nodejs
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Ensure firewalld is stopped (testing scenario)
      service:
        name: ufw
        state: stopped

    - name: Install Forever (to run our Node.js app)
      npm:
        name: forever
        global: yes
        state: present



